
({
	baseUrl: "src",
	name: "components/nurbs",
	out: "dist/components/nurbs.js",
	optimize: "none",
	mainConfigFile: "src/components/nurbs.config.js",
	exclude: [
		"jquery",
		"text",
		"jquery-mousewheel",
		"pako_inflate",
		"libtess",
		"opentype",
		"bezier",
		"sprintf",
		"x_ite/Fields",
		"x_ite/Basic/X3DFieldDefinition",
		"x_ite/Basic/FieldDefinitionArray",
		'x_ite/Browser/Core/Shading',
		"x_ite/Components/Core/X3DSensorNode",
		"x_ite/Components/Core/X3DNode",
		"x_ite/Components/Core/X3DChildNode",
		'x_ite/Components/Geometry3D/Extrusion',
		"x_ite/Components/Grouping/X3DBoundedObject",
		'x_ite/Components/Interpolation/OrientationInterpolator',
		'x_ite/Components/Interpolation/PositionInterpolator',
		'x_ite/Components/Interpolation/X3DInterpolatorNode',
		'x_ite/Components/Rendering/X3DCoordinateNode',
		'x_ite/Components/Rendering/X3DGeometricPropertyNode',
		'x_ite/Components/Rendering/X3DGeometryNode',
		'x_ite/Components/Rendering/X3DLineGeometryNode',
		"x_ite/Configuration/SupportedNodes",
		"x_ite/Bits/X3DConstants",
		"x_ite/Bits/X3DCast",
		"standard/Math/Numbers/Vector3",
		"standard/Math/Numbers/Rotation4",
		"standard/Math/Numbers/Quaternion",
		"standard/Math/Numbers/Matrix4",
		'standard/Math/Geometry/Line3',
		'standard/Math/Geometry/Plane3',
		'standard/Math/Geometry/Triangle2'
	],
	wrap: {
		startFile: "build/parts/nurbs.start.frag",
		endFile: "build/parts/nurbs.end.frag"
	},
})
