- title: "Textures, Lights, and Environment"
  children:
    - title: "Mapping Textures"
      url: /tutorials/mapping-textures/
    - title: "Controlling How Textures are Mapped"
      url: /tutorials/controlling-how-textures-are-mapped/
    - title: "Lighting Your World"
      url: /tutorials/lighting-your-world/
    - title: "Adding Backgrounds"
      url: /tutorials/adding-backgrounds/
    - title: "Adding Fog"
      url: /tutorials/adding-fog/
    - title: "Adding Sound"
      url: /tutorials/adding-sound/
    - title: "Controlling the Viewpoint"
      url: /tutorials/controlling-the-viewpoint/
    - title: "Controlling Navigation"
      url: /tutorials/controlling-navigation/
    - title: "Sensing the Viewer"
      url: /tutorials/sensing-the-viewer/
