# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", "~> 7.3"

group :test do
  gem "html-proofer", "~> 5.0"
end

group :jekyll_plugins do
  gem 'jekyll-redirect-from'
  gem 'jekyll-x3d', '~> 1.0'
  gem 'jekyll-vrml', '~> 2.2'
end
