# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", "~> 7.5"

gem "html-proofer", "~> 5.0", group: :test

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.2.0", :platforms => [:windows]

group :jekyll_plugins do
  gem 'jekyll-redirect-from'
  gem 'jekyll-x3d', '~> 1.0'
  gem 'jekyll-vrml', '~> 2.2'
end
