# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", "~> 7.0"

group :test do
  gem "html-proofer", "~> 5.0"
end

group :jekyll_plugins do
  gem 'jekyll-vrml', '~> 2.0'
end
